spring:
  application:
    name: task-card-service

  datasource:
    url: jdbc:mysql://localhost:3306/card-task-db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sa
    password: Password#123
  main:
    allow-circular-references: true
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

access-token:
  private: classpath:certs/access-token-private.key
  public: classpath:certs/access-token-public.key
refresh-token:
  private: classpath:certs/refresh-token-private.key
  public: classpath:certs/refresh-token-public.key

server:
  port: 8080
  error:
    include-message: always

jwt:
  signing-key: B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration-time: 1800000

springdoc:
  version: 1.0
  writer-with-order-by-keys: true
  swagger-ui:
    tryItOutEnabled: true
    filter: true
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
    use-root-path: true
    path: /swagger-ui-custom.html
  show-actuator: true
  openapi:
    host: http://localhost
    url: ${springdoc.openapi.host}:8080/task-card-service
  api-docs:
    resolve-schema-properties: true
    path: /v3/api-docs